// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Q0ACi2NeX2ccw-kE8qSUlss5d-nKN4I',
    appId: '1:660952689240:web:2a20f0d16bf915c1d7b82d',
    messagingSenderId: '660952689240',
    projectId: 'vazifa66-affdf',
    authDomain: 'vazifa66-affdf.firebaseapp.com',
    storageBucket: 'vazifa66-affdf.appspot.com',
    measurementId: 'G-ESCLZCY7G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVt2d6gEIIPQLOeSsQg6p-lM889dOXdbg',
    appId: '1:660952689240:android:cf71cae7fc26b317d7b82d',
    messagingSenderId: '660952689240',
    projectId: 'vazifa66-affdf',
    storageBucket: 'vazifa66-affdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8rBsis-So7B_4kIjWLzAYZmX_L_JCpV0',
    appId: '1:660952689240:ios:51fe7a7c92de87e8d7b82d',
    messagingSenderId: '660952689240',
    projectId: 'vazifa66-affdf',
    storageBucket: 'vazifa66-affdf.appspot.com',
    iosBundleId: 'com.example.amaliyotVazifa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Q0ACi2NeX2ccw-kE8qSUlss5d-nKN4I',
    appId: '1:660952689240:web:bb7a3024851e899dd7b82d',
    messagingSenderId: '660952689240',
    projectId: 'vazifa66-affdf',
    authDomain: 'vazifa66-affdf.firebaseapp.com',
    storageBucket: 'vazifa66-affdf.appspot.com',
    measurementId: 'G-88WHB0T4KZ',
  );
}
